apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-12-28T05:29:52Z"
  generation: 1
  labels:
    app: credit-api
  name: credit-api
  namespace: default
  resourceVersion: "91572"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/credit-api
  uid: 12ea0036-2933-11ea-adc4-42010a800229
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: credit-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: credit-api
    spec:
      containers:
      - image: gcr.io/upbeat-handler-263217/credit@sha256:be9771e1bd0574e9afad73b127849990c8bda206de17e50d3f7a1337f26cc0f5
        imagePullPolicy: Always
        name: credit
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

