apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: credit-api
  labels:
    app: credit-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-api
  template:
    metadata:
      labels:
        app: credit-api
    spec:
      containers:
        - image: gcr.io/app-cluster-263807/credit:latest
          name: credit
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 9001
            initialDelaySeconds: 120
            periodSeconds: 5000