apiVersion: "v1"
kind: "Service"
metadata:
  name: "credit-api-service"
  namespace: "default"
  labels:
    app: "credit-api"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 9000
  selector:
    app: "credit-api"
  type: "LoadBalancer"
  loadBalancerIP: ""
