apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-12-28T05:35:32Z"
  labels:
    app: credit-api
  name: credit-api-service
  namespace: default
  resourceVersion: "93113"
  selfLink: /api/v1/namespaces/default/services/credit-api-service
  uid: dd550d7f-2933-11ea-adc4-42010a800229
spec:
  clusterIP: 10.12.1.239
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 31582
      port: 80
      protocol: TCP
      targetPort: 9000
  selector:
    app: credit-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 35.232.116.5
