name: Deploy CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [edited, closed]
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Create and push image to GCP
        uses: mr-smithers-excellent/docker-build-push@v1.0
        with:
          image: upbeat-handler-263217/credit
          tag: latest
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.DOCKER_PASSWORD }}
