name: Credit App CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Create and push image to GCP
        uses: mr-smithers-excellent/docker-build-push@v1.0
        with:
          image: gcr.io/upbeat-handler-263217/credit
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.DOCKER_PASSWORD }}